# Generated by Django 6.0.5 on 2026-05-25 11:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApproximateDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approximation', models.CharField(max_length=2)),
                ('additional_notes', models.CharField(blank=True, max_length=50, null=True, verbose_name='short description of approx')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='attendance designation')),
                ('additional_notes', models.CharField(blank=True, max_length=250, null=True, verbose_name='short description of presence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='event designation')),
                ('additional_notes', models.CharField(blank=True, max_length=250, null=True, verbose_name='short description of type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='instrument')),
                ('additional_notes', models.CharField(blank=True, max_length=250, null=True, verbose_name='additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LanguageCode',
            fields=[
                ('language_code', models.CharField(max_length=7, primary_key=True, serialize=False, verbose_name='language code')),
            ],
        ),
        migrations.CreateModel(
            name='PollAttendanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90, unique=True, verbose_name='poll type')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='name of role')),
                ('additional_notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='short explanation of role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='name of skill')),
                ('additional_notes', models.CharField(blank=True, max_length=255, null=True, verbose_name='short explanation of skill')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='voice')),
                ('additional_notes', models.CharField(blank=True, max_length=250, null=True, verbose_name='additional notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=250, unique=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name of the event')),
                ('location', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(verbose_name='start date hour')),
                ('ended_at', models.DateTimeField(verbose_name='end date hour')),
                ('details', models.TextField(blank=True, null=True)),
                ('num_visitors', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('producers', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncope.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='EventSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('encore', models.BooleanField(blank=True, null=True, verbose_name='additional songs after the end (encore)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncope.event')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='Organization auth hook', on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='name')),
                ('last_name', models.CharField(max_length=100, verbose_name='surname')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=23, null=True)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('death_date', models.DateField(blank=True, null=True, verbose_name='deathday')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('birth_approximate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='birth_approximate', to='syncope.approximatedate')),
                ('death_approximate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='death_approximate', to='syncope.approximatedate')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owned_persons', to='syncope.person')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumentalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncope.instrument')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncope.person')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PollEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(verbose_name='start date hour')),
                ('ended_at', models.DateTimeField(verbose_name='end date hour')),
                ('details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncope.eventtype')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_events', to='syncope.poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_persons', to='syncope.person')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_persons', to='syncope.poll')),
            ],
        ),
        migrations.CreateModel(
            name='PollAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, max_length=50, null=True)),
                ('poll_attendance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_attendances', to='syncope.pollattendancetype')),
                ('poll_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_attendances', to='syncope.pollevent')),
                ('poll_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_attendances', to='syncope.pollperson')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('details', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('guests', models.ManyToManyField(blank=True, related_name='projects', to='syncope.person')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='syncope.project'),
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True, verbose_name='url')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PersonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_resource', to='syncope.person')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_resource', to='syncope.resource')),
            ],
        ),
        migrations.CreateModel(
            name='EventSongResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('event_song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_song_resource', to='syncope.eventsong')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_song_resource', to='syncope.resource')),
            ],
        ),
        migrations.CreateModel(
            name='EventResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_resource', to='syncope.event')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_resource', to='syncope.resource')),
            ],
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_role', to='syncope.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_role', to='syncope.role')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='persons', through='syncope.PersonRole', to='syncope.role'),
        ),
        migrations.CreateModel(
            name='MembershipPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateField()),
                ('ended_at', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_period', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_period', to='syncope.person')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_period', to='syncope.role')),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(max_length=32, unique=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share', to='syncope.event')),
                ('poll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share', to='syncope.poll')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share', to='syncope.project')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='share', to='syncope.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ShareVisit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('counter', models.PositiveIntegerField(default=0)),
                ('share', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_visits', to='syncope.share')),
            ],
        ),
        migrations.CreateModel(
            name='PersonSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_skill', to='syncope.person')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='person_skill', to='syncope.skill')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='persons', through='syncope.PersonSkill', to='syncope.skill'),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('number_of_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_copies', models.PositiveIntegerField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='year of creation')),
                ('group', models.CharField(max_length=250, verbose_name='type of song')),
                ('number_of_voices', models.PositiveIntegerField(blank=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=255, null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='duration in seconds')),
                ('lyrics', models.TextField(blank=True, null=True, verbose_name='lyrics')),
                ('composer', models.ForeignKey(limit_choices_to={'person_skill__skill_id': 1}, on_delete=django.db.models.deletion.PROTECT, related_name='composed_songs', to='syncope.person')),
                ('languagecode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='syncope.languagecode')),
                ('poet', models.ForeignKey(limit_choices_to={'person_skill__skill_id': 2}, on_delete=django.db.models.deletion.PROTECT, related_name='written_songs', to='syncope.person')),
                ('translator', models.ForeignKey(blank=True, limit_choices_to={'person_skill__skill_id': 7}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='translated_songs', to='syncope.person')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('bar_number', models.CharField(blank=True, max_length=20, null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='syncope.song')),
            ],
            options={
                'ordering': ['word'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='projects', to='syncope.song'),
        ),
        migrations.CreateModel(
            name='LyricsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('languagecode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncope.languagecode')),
                ('translator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='syncope.person')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncope.song')),
            ],
        ),
        migrations.AddField(
            model_name='eventsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncope.song'),
        ),
        migrations.CreateModel(
            name='SongResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='song_resource', to='syncope.resource')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='song_resource', to='syncope.song')),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncope.person')),
                ('voice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncope.voice')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='syncope.person')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'person'), name='unique_membership_per_user_person')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncope.attendancetype')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncope.event')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='syncope.person')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'person'], name='syncope_att_event_i_aa08bf_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'person'), name='unique_person_per_event')],
            },
        ),
        migrations.AddConstraint(
            model_name='pollevent',
            constraint=models.UniqueConstraint(fields=('poll', 'location', 'started_at', 'ended_at'), name='unique_poll_location_date'),
        ),
        migrations.AddConstraint(
            model_name='pollperson',
            constraint=models.UniqueConstraint(fields=('poll', 'person'), name='unique_person_per_poll'),
        ),
        migrations.AddConstraint(
            model_name='personrole',
            constraint=models.UniqueConstraint(fields=('person', 'role'), name='unique_role_per_org_person'),
        ),
        migrations.AddIndex(
            model_name='membershipperiod',
            index=models.Index(fields=['user', 'started_at', 'ended_at'], name='syncope_mem_user_id_8d8b76_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipperiod',
            index=models.Index(fields=['person', 'started_at', 'ended_at'], name='syncope_mem_person__660a3e_idx'),
        ),
        migrations.AddConstraint(
            model_name='share',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('event_id__isnull', True), ('poll_id__isnull', True), ('project_id__isnull', True), ('resource_id__isnull', False)), models.Q(('event_id__isnull', True), ('poll_id__isnull', False), ('project_id__isnull', True), ('resource_id__isnull', True)), models.Q(('event_id__isnull', False), ('poll_id__isnull', True), ('project_id__isnull', True), ('resource_id__isnull', True)), models.Q(('event_id__isnull', True), ('poll_id__isnull', True), ('project_id__isnull', False), ('resource_id__isnull', True)), _connector='OR'), name='share_only_one_fk'),
        ),
        migrations.AddConstraint(
            model_name='personskill',
            constraint=models.UniqueConstraint(fields=('person', 'skill'), name='unique_skill_per_org_person'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_per_person'),
        ),
        migrations.AddConstraint(
            model_name='song',
            constraint=models.UniqueConstraint(fields=('user', 'internal_id'), name='unique_id_per_org'),
        ),
        migrations.AddConstraint(
            model_name='eventsong',
            constraint=models.UniqueConstraint(fields=('event', 'order'), name='unique_order_per_event'),
        ),
    ]
