# Generated by Django 6.0.5 on 2026-05-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syncope', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='uri',
            new_name='url',
        ),
    ]
