# Generated by Django 6.1 on 2026-09-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('syncope', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='details',
        ),
    ]
