# Generated by Django 6.1 on 2026-09-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncope', '0002_remove_event_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='excluded_members',
            field=models.ManyToManyField(blank=True, help_text="Members otherwise active during the project's date range, removed from its participant list.", related_name='excluded_from_projects', to='syncope.person'),
        ),
    ]
