# Generated by Django 6.1 on 2026-09-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncope', '0003_project_excluded_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(blank=True, max_length=250, verbose_name='name of the event'),
        ),
    ]
